
# datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/sampledb
    username: username
    password: password
    initialization-mode: always
  h2: 
    console: 
      enabled: true